Milestone two
Arinpe/Bookstore pull request #2
Opened 2021-09-20 19:33 UTC by Arinpe

This is a Bookstore application, where users get to display the books they have read or currently reading. This app is built with React and Redux

2021-09-20 21:05 UTC, e71az requested changes
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hello @Arinpe, I am Elias, your reviewer for this PR

Well done so far with your project!

I will mention to you a small summary of things that need to be changed in order to keep moving:

- [ ] I was unable to run your project successfully, this is the error that I am getting, please fix it to be able to display content on the page: 
![image](https://user-images.githubusercontent.com/38522578/134075431-c33fcbfa-efc4-4072-9b27-b85a74bd2a31.png)
- [ ] Please check the comments below for additional changes needed.

Please correct those issues and send another review request, good luck, and well done so far! 

Code review by Elias Castañeda

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-09-20 21:05 UTC, eliasecasta commented on src/index.js
> +
- [ ] it adds example books to initial state object [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/InitialBooks.png) (You need to initialize your sample books here please)

2021-09-20 21:05 UTC, eliasecasta commented on src/App.js
> +import React from 'react';
- [x] it is placed in `src/components` directory (Right now it is in src, please fix this to comply with the project requirements)

2021-09-20 21:05 UTC, eliasecasta commented on src/common.js
> +  // },
- [x] Please remove all the commented code that you may have left.

2021-09-20 21:05 UTC, e71az commented on src/actions/index.js
> +export const removeBook = (id) => ({
- Contains `CREATE_BOOK` and `REMOVE_BOOK` actions with Book objects as an argument [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/ReduxActions/ReducxActions.png) (Both actions should receive the book object as an argument, I understand that deletion by ID is not a bad idea but the project requires it like this, please change it)

2021-09-21 21:30 UTC, george-shammar requested changes
Hi @Arinpe , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

- [ ] I couldn't run your application for the same reason mentioned by the previous reviewer. Please, let's fix it. :pray: 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-09-21 21:30 UTC, george-shammar commented on src/App.js
> +    <BookForm />
- [ ] As highlighted by the previous reviewer, the `App.js` component is still in the `src` folder. Please, implement it inside `src/component` as per the project requirement.

2021-09-21 21:30 UTC, george-shammar commented on src/index.js
> +    <React.StrictMode>
- [ ] As highlighted by the previous reviewer, please implement your sample book object here (index.js).

2021-09-23 20:27 UTC, rukundoeric approved these changes
Hi @Arinpe,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------

2021-09-24 10:04 UTC, merged